name             'lemp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures lemp'
long_description 'Installs/Configures lemp'
version          '0.1.0'

depends 'nginx', '=2.7.6'
depends 'php-fpm', '=0.7.6'
depends 'mysql', '=8.1.0'
depends 'simple_iptables', '=0.8.0'
depends 'openssh', '=2.1.0'
